CREATE TABLE "ads" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"type" text DEFAULT 'banner' NOT NULL,
	"placement" text DEFAULT 'home_top' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"title" text NOT NULL,
	"subtitle" text,
	"cta_text" text,
	"image_url" text,
	"link" text NOT NULL,
	"category" text,
	"impressions" integer DEFAULT 0,
	"clicks" integer DEFAULT 0,
	"priority" integer DEFAULT 0,
	"start_date" timestamp,
	"end_date" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
